# Configuration des services AppWoyofal
services:
  # Repositories
  repositories:
    ClientRepository:
      class: App\Repository\ClientRepository
      dependencies:
        - PDO
      singleton: true

    LoggerRepository:
      class: App\Repository\LoggerRepository
      dependencies:
        - PDO
      singleton: true

    CompteurRepository:
      class: App\Repository\CompteurRepository
      dependencies:
        - PDO
      singleton: true

    TrancheRepository:
      class: App\Repository\TrancheRepository
      dependencies: []
      singleton: true

  # Services
  services:
    LoggerService:
      class: App\Service\LoggerService
      dependencies:
        - LoggerRepository
      singleton: true

    TrancheService:
      class: App\Service\TrancheService
      dependencies: []
      singleton: true

    CompteurService:
      class: App\Service\CompteurService
      dependencies:
        - CompteurRepository
      singleton: true

    AchatService:
      class: App\Service\AchatService
      dependencies:
        - CompteurRepository
        - TrancheRepository
        - ClientRepository
        - LoggerService
      singleton: true

    ClientService:
      class: App\Service\ClientService
      dependencies:
        - ClientRepository
        - LoggerService
        - AchatService
        - CompteurService
        - TrancheService
      singleton: true

  # Controllers
  controllers:
    ClientController:
      class: App\Controller\ClientController
      dependencies:
        - ClientService
      singleton: true

  # Core Services
  PDO:
    factory: App\Core\Database::getConnection
    singleton: true

# Configuration base de données
database:
  host: ${DB_HOST:postgres}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:AppWoyofal}
  user: ${DB_USER:pguserWoyofal}
  password: ${DB_PASSWORD:pgpassword}

# API
api:
  base_url: ${API_BASE_URL:http://localhost:8081}